### ISSUE TITLE
Use Nix instead of venv?

### ISSUE THREAD

**Issue by Mr-Andersen** [IntersectMBO/cardano-node-tests#1048]
Currently the repo uses both Nix and venv to create dev environments. It's possible to dispose of venv and only use Nix. It would make development and test runs cleaner and easier to perform.
I can implement this myself.

**Comment by mkoura** [comment]
Hey! You can run `nix-shell` in root of the repo and you'll have everything that is needed for running the tests (we run our nightly jobs this way).

For development we need to use some packages in "editable" mode (`pip install -e ...`), not sure if that would work with nix? Namely [cardano-clusterlib](https://pypi.org/project/cardano-clusterlib/) where we often need to make changes and test it together with cardano-node-tests.

**Comment by Mr-Andersen** [comment]
@mkoura oh, nice, you should mention that in readme :) However, when I call `make lint` from under nix-shell, it reports:
```
$ make lint
pre-commit run -a
make: pre-commit: No such file or directory
make: *** [Makefile:16: lint] Error 127
```
Are Nix and venv not in parity?

**Comment by Mr-Andersen** [comment]
This fixes it:
```diff
diff --git a/nix/default.nix b/nix/default.nix
index c342e8cd..ed087666 100644
--- a/nix/default.nix
+++ b/nix/default.nix
@@ -53,6 +53,7 @@ let
           requests
           psycopg2
           pandas
+          pre-commit
         ])) ];
       });
     });
```
