### ISSUE TITLE
Auto-balance multi-assets

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#1371]
https://github.com/input-output-hk/cardano-node/issues/4453

**Comment by saratomaz** [comment]
**blocked** until fix on [cardano-node](https://github.com/input-output-hk/cardano-node/pull/4450) regression tests are failing, impossible to mint:


![Screenshot from 2022-10-28 14-45-02](https://user-images.githubusercontent.com/97231749/198620596-06479dde-e562-4520-ab0c-9f43c24735e0.png)

**Comment by mkoura** [comment]
Done
