### ISSUE TITLE
Run tests which require network timeout using the same config as mainnet

### ISSUE THREAD

**Issue by coot** [IntersectMBO/cardano-node-tests#1424]
Test which _do not involve_ network timeouts & delays (e.g. shutting down nodes), one can run using a face pace blockchain (e.g. small `k`, etc).  However for tests which _do involve_ them, we should run them using the same parameters as `mainnet`.  In first iteraction we could do even something simple as running a single eara in which we check if nodes can be disconnected and they will reconnect.  A more advanced setup, would require a fast forward transition to the most recent era, in which parameters would change to what `mainnet` is using and then run network tests.

**Comment by mkoura** [comment]
We added a testnet setup with the same parameters as mainnet and use the testnet for reconnection tests.
