### ISSUE TITLE
Governance Action: New Constitution Governance Action

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2023]
1. The community would like to amend the constitution
2. Public discussion takes place in the Cardano Forum and elsewhere
3. The {SanchoNet} Civics Committee considers the amendment
4. An amendment is prepared, including a hash of the current constitution
5. A specific New Constitution governance action is prepared that links to the discussion and to the previous constitution action and includes the anchor for the new constitution
6. The action is submitted on-chain - fee plus deposit paid by the submitter
7. The constitutional committee confirms the action is constitutional
8. DReps vote
9. If the action gets enough DRep votes before it expires, it is ratified
10. The amendment to the constitution is recorded on-chain from the following epoch

**Comment by mkoura** [comment]
Test added.
