### ISSUE TITLE
Governance Action: Hard Fork Initiation

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2025]
1. Discussions on the content of the hard fork take place on the Cardano Forum
2. The community agrees that it wants to Hard Fork from Conway (protocol version 9) to the next era on or after the 21st November 2023
3. A specific Info governance action is prepared that links to the text of the proposal
4. The action is submitted on-chain - fee plus deposit paid by the submitter
5. The constitutional committee confirms the action is constitutional
6. SPOs and DReps vote on the Info action
7. The Info action reaches the time limit and expires
8. The Info action deposit is returned to the submitter
9. The result of the Info action can be determined from the total Yes/No/Abstain votes
10. If the action is not passed, no further action is taken
11. Otherwise, a hard fork governance action is prepared that links to the result of the Info poll/discussions and to the previous hard fork action, and that increments the major Protocol Version to 10
12. The action is submitted on-chain on SanchoNet on the 20th November 2023
13. The constitutional committee confirms the action is constitutional 
14. SPOs upgrade their nodes to a node version that can handle the new protocol version
15. DReps and SPOs vote
16. If the action gets enough votes before the expiry date, it is ratified.
17. The hard fork happens one epoch after ratification

**Comment by mkoura** [comment]
Tests added.
