### ISSUE TITLE
Governance Action: Motion of No-Confidence

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2026]
1. The community discusses the constitutional committee actions on the Cardano Forum 
2. The community agrees that it has no confidence in the constitutional committee
3. A no-confidence governance action is prepared that links to the discussions
4. The action is submitted on chain on SanchoNet 
5. DReps and SPOs vote
6. If the action gets enough votes before the expiry date, it is ratified.
7. The governance system enters a state of no confidence one epoch after ratification (the next day on SanchoNet) and no further actions can then be enacted on chain
8. 7 community members stand as a new constitutional committee and are confirmed by a popular vote on the Cardano Forum, which confirms a threshold of 5/7
9. A new constitutional committee governance action is prepared that links to the discussions and the previous constitutional committee action, including the keys for the new committee members and a threshold fraction of 5/7
10. The action is submitted on chain on SanchoNet 
11. DReps and SPOs vote
12. If the action gets enough votes before the expiry date, it is ratified.
13. The new constitutional committee takes office immediately on ratification, and can vote on any new/outstanding governance actions

**Comment by mkoura** [comment]
Tests added.
