### ISSUE TITLE
Governance Action: Multiple Treasury Withdrawals

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2027]
1. The community discusses a proposal on the Cardano Forum to distribute 500,000 SanchoAda to Alice from the SanchoNet treasury 
2. The community independently discusses a second proposal on the Cardano Forum to distribute 300,000 SanchoAda to Bob from the SanchoNet treasury
3. The community independently discusses a third proposal on the Cardano Forum to distribute 100,000 SanchoAda to Alice and 500,000 SanchoAda to Mallory from the SanchoNet treasury
4. The community agrees that it wants to fund the first and third proposals
5. A treasury withdrawal governance action is prepared that links to the discussions and moves 600,000 SanchoAda to Alice’s address and 500,000 SanchoAda to Mallory’s address
6. The action is submitted on chain on SanchoNet 
7. The constitutional committee confirms the action is constitutional
8. DReps vote
9. If the action gets enough votes before the expiry date, it is ratified.
10. The treasury withdrawal happens immediately on ratification

**Comment by mkoura** [comment]
Tests added.
