### ISSUE TITLE
Governance Action: Treasury Withdrawal

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2028]
1. The community discusses a proposal on the Cardano Forum from the SanchoTrust trustees to obtain 1,000,000 SanchoAda from the SanchoNet treasury 
2. The community agrees that it wants to fund the proposal
3. A treasury withdrawal governance action is prepared that links to the discussions and moves 1,000,000 SanchoAda to the SanchoTrust address
4. The action is submitted on-chain on SanchoNet 
5. The constitutional committee confirms the action is constitutional
6. DReps vote
7. If the action gets enough votes before the expiry date, it is ratified.
8. The treasury withdrawal happens immediately on ratification

**Comment by mkoura** [comment]
Tests added.
