### ISSUE TITLE
Governance Action: Update a Single Protocol Parameter - Success

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2030]
1. Some SPOs want to reduce minpoolcost
2. SPO community is polled/discussions take place
3. Parameter committee advises on impact of change and makes an expert recommendation
4. A specific parameter change governance action is prepared that links to the polls/discussions/expert advice and to the previous parameter change action
 `Eg Reduce minpoolcost to 170 ada`
6. The action is submitted on chain - fee plus deposit paid by the submitter
7. The constitutional committee confirms the action is constitutional
8. DReps vote
9. If the action gets enough votes before the expiry date, it is ratified
10. The minpoolcost parameter is automatically changed to 170 ada when it is enacted (one epoch after ratification = 1 day on SanchoNet) and the action deposit is returned to the submitter

**Comment by mkoura** [comment]
Tests added.
