### ISSUE TITLE
Governance Action: Update a Single Protocol Parameter - Expiry

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2031]
1. A community member wants to judge support for their proposed CIP
2. Public discussion takes place in the Cardano Forum and elsewhere
3. A specific Info governance action is prepared that links to the discussion
4. The action is submitted on-chain - fee plus deposit paid by the submitter
5. The constitutional committee confirms the action is constitutional
6. SPOs and DReps vote
7. The action reaches the time limit and expires
8. The Info action deposit is returned to the submitter
9. The result of the Info action can be determined from the total Yes/No/Abstain votes and used to justify moving the CIP to implementation

**Comment by mkoura** [comment]
Tests added.
