### ISSUE TITLE
Tx generator

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#433]
Create an option/tool to generate a configurable number of parallel transactions.

**Scope**
- have a fast way to generate load on a specific environment
- monitor the environments under load
- compare results over time 
- send txs over a specified time (like - send 10 txs/min/hour per second for 20 mins/hours).

**Out of scope**
- precise measurement of metrics like - tps (txs per second), propagation time, etc

**The tool should take as input**
- desired environment - shelley_qa, testnet, staging, mainnet, local, etc
- no of transactions 
- how much time to wait after submitting the txs
- if ADA only or include also multi-assets

**Methodology** (proposal)
- create source and destination addresses for the txs
- fund the source addresses
- create the offline txs
- send the offline txs as fast as possible
- wait for some time (a configurable amount, or until local mempool = 0, or a specific no of blocks after the last tx was submitted)

**Return the results**
- how many txs were created/sent
- how many txs were processed by the blockchain, based on the destination balances
- how many txs were not processed, based on the source balances
- how much time it required to: create/send/process the txs
- node version used - tag no, commit not
- DateTime for the test

**Clean up**
- store the results into a DB - to define the structure of the DB in order to improve the trackability of the results
- display the results into a visual dashboard - similar to the sync tests (only an idea)
- send all the funds back to the faucet address

**Open questions**
- what is the simplest way to trigger the run of this test?
- how can we make sure we use the same machine each time - in order to have comparable results? (do we want this?)
- would it make sense to have this test triggered from the Github Actions UI interface? 
- could we configure the node in order to collect the test results into a Grafana dashboard? (like CPU. RAM, TXs processed, block sync status, mempool txs)

**Comment by dorin100** [comment]
more details: https://input-output-rnd.slack.com/archives/C4Q7MF25U/p1618037194091700

**Comment by mkoura** [comment]
Done by perf team in their testing.
