### ISSUE TITLE
db-sync values checks

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#463]
Check that:
- [ ] [sum of transaction sizes for a block does not exceed block size](https://github.com/input-output-hk/cardano-db-sync/issues/1045)
- [ ] there are values for all the epochs
- [ ] blocks timestamps or any timestamps should not be in the future, only in the past
- [ ] the start_time and end_time for each block should be the time stamp on the first block and last block of the epoch respectively
- [ ] data (for blocks, slots, epochs) don’t have negative values
- [ ] epochs, block numbers should be increased by 1, we can’t have missing epochs, slots and etc. in tables

**Comment by ArturWieczorek** [comment]
As for the first item on the list - from `cardano-db-sync` schema documentation:

>The block size (in bytes). Note, this size value is not expected to be the same as the sum of the tx sizes due to the fact that txs being stored in segwit format and oddities in the CBOR encoding.
