### ISSUE TITLE
check 'ada_pots' table values

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#776]
details here: https://github.com/input-output-hk/cardano-db-sync/issues/942

**Comment by saratomaz** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/434dc9e78c1bfe12ce7e763ac9783c526cb41cc0/cardano_node_tests/tests/test_update_proposals.py#L67

**Comment by mkoura** [comment]
Done
