### ISSUE TITLE
Check signature of the KES hot key on kes-period-info command

### ISSUE THREAD

**Issue by saratomaz** [IntersectMBO/cardano-node-tests#979]
**What is expected**
The signature of the KES hot key should be valid.

_cardano-node ticket:_
#3556

**Scenarios**
1. Fails if the signature of the KES hot key, counter and KES period start specified in the operational certificate is invalid (the cold key did not authorize the hot key)
2. Fails if the signature of the KES hot key specified in the block header body is invalid (the hot key in the operational certificate did not authorize the block)

**Comment by mkoura** [comment]
Done
